# Generated by Django 5.2.4 on 2025-08-23 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_healtharticle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healtharticle',
            name='is_published',
        ),
    ]
