# Generated by Django 5.2.4 on 2025-07-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='symptoms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
