# Generated by Django 5.2.4 on 2025-08-02 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_appointment_symptoms'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DoctorSchedule',
            new_name='TimeSlot',
        ),
    ]
