# Generated by Django 5.2.4 on 2025-07-29 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctoravailability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_monday', models.BooleanField(default=False)),
                ('work_tuesday', models.BooleanField(default=False)),
                ('work_wednesday', models.BooleanField(default=False)),
                ('work_thursday', models.BooleanField(default=False)),
                ('work_friday', models.BooleanField(default=False)),
                ('work_saturday', models.BooleanField(default=False)),
                ('work_sunday', models.BooleanField(default=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
