# Generated by Django 5.2.4 on 2025-08-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctorschedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctoravailability',
            options={'ordering': ['day_of_week'], 'verbose_name': 'Doctor Availability', 'verbose_name_plural': 'Doctor Availabilities'},
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='end_time',
            field=models.TimeField(help_text='End of working hours'),
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='start_time',
            field=models.TimeField(help_text='Start of working hours'),
        ),
        migrations.DeleteModel(
            name='DoctorSchedule',
        ),
    ]
