# Generated by Django 5.2.4 on 2025-08-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_alter_doctoravailability_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to deactivate without deleting'),
        ),
        migrations.AddField(
            model_name='medication',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price per unit (e.g., per tablet, per ml)', max_digits=10),
        ),
        migrations.AddField(
            model_name='medication',
            name='unit',
            field=models.CharField(default='tablet', help_text='Unit of sale: tablet, ml, vial, etc.', max_length=50),
        ),
        migrations.AddField(
            model_name='prescription',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, help_text='Number of days to take', null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='frequency',
            field=models.CharField(blank=True, help_text='e.g., Once daily, Twice a day, Every 6 hours', max_length=100),
        ),
        migrations.AddField(
            model_name='prescription',
            name='line_total',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total cost for this medication', max_digits=10),
        ),
        migrations.AddField(
            model_name='prescription',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Total units to dispense (auto-filled)'),
        ),
    ]
