# Generated by Django 5.2.4 on 2025-08-05 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_medication_is_active_medication_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='interactions',
        ),
        migrations.AddField(
            model_name='medication',
            name='safety_warnings',
            field=models.TextField(blank=True, help_text="e.g., 'Avoid alcohol', 'Do not combine with Warfarin', 'May cause drowsiness'"),
        ),
    ]
