# Generated by Django 5.2.4 on 2025-08-06 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_medicineinventory'),
        ('patients', '0004_alter_timeslot_options_alter_timeslot_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='appointment',
            field=models.ForeignKey(blank=True, help_text='The appointment during which this was prescribed', null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.appointment'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='frequency',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='line_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
