# Generated by Django 5.2.4 on 2025-08-08 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0012_diagnosisnote_appointment_alter_diagnosisnote_doctor_and_more'),
        ('patients', '0006_medicalvisit_delete_medicalhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosisnote',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.appointment'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.appointment'),
        ),
    ]
